# 虚拟机box镜像模板
box: "AlmaLinux-8"
http_proxy: "http://6.86.3.12:3128/"
no_proxy: "localhost,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,127.0.0.0/8,6.86.0.0/16"

server:
  count: 1
  cpus: 2
  memory: 4096
  
node:
  count: 2
  cpus: 2
  memory: 2048

ip:
  # server节点的第一个IP，后续IP会根据创建数量，自动加1
  server: 192.168.56.11
  # node节点的第一个IP，后续IP会根据创建数量，自动加1
  node:   192.168.56.101